language: cpp
branches:
  only:
  - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: hypro
    - DOXYFILE: $TRAVIS_BUILD_DIR/build/doc/Doxygen
    - GH_REPO_REF: github.com/hypro/hypro.git

notifications:
  email:
    recipients:
      - stefan.schupp@cs.rwth-aachen.de
  slack:
    rooms:
      - hypro:v2n2cgATRJJYPctLTL1MSfOn#github

sudo: required

matrix:
  include:
    #- os: linux
    #  compiler: gcc
    #  env: COMPILER=g++-4.9
    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-5
    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-6 FLAGS=-DHYPRO_COVERAGE=ON
    - os: linux
      dist: trusty
      compiler: clang
      env: COMPILER=clang++-3.6
    - os: linux
      dist: trusty
      compiler: clang
      env: COMPILER=clang++-3.7
    - os: linux
      dist: trusty
      compiler: clang
      env: COMPILER=clang++-3.8

before_install:
  - cd .travis/ && source setupTravis.sh && cd ../
  - git clone https://github.com/smtrat/carl.git && cd carl && mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make lib_carl

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build && cmake $FLAGS -DCMAKE_CXX_COMPILER=$COMPILER .. && make resources && make
  - make test

# Generate and deploy documentation
after_success:
  - cmake -DCREATE_DOC=ON ..
  - cd $TRAVIS_BUILD_DIR
  - chmod +x createAndDeployDocumentation.sh
  - ./createAndDeployDocumentation.sh
  # coveralls
  - chmod +x processCoverage.sh
  - ./processCoverage.sh
