branches:
  only:
  - master

language: cpp

os:
  - linux

sudo: required
dist: trusty

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get install cmake gcc-4.9 g++-4.9 libboost1.55-all-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - cd && mkdir carl && cd carl && git clone https://github.com/smtrat/carl.git && cd carl && mkdir build && cd build && cmake .. && make lib_carl
  - ls
  - cd ../../../
  - ls

install: true

before_script: true

script: ls && mkdir build && cd build && cmake .. && make
