language: cpp
os:
  - linux
compiler:
  - gcc

# Environment variables
env:
  global:
    - secure: "Eeh/FOuAjzN6WIPWkdjGXMRbZudVDSt8M+pF/rfmjTREPo73cbBUvANkPoILm4wpnNxRYnBD8tLXeaZk+x+HkjTX7d4BJK9wzAGQtBROzPQCdhTGjA3FmQx2D7Iby66BEQuBwWRwn2IfUJTkh4EF2c0pA2EdEeqraLLWswYjhP4BxDGw1dch0C9N6ATJE0OPC1H8VPsGzLDsLxas8ai2np1aDKTSZ6fk6h3Bj/5Y7eTF7jNbn8CjMY7lCVn9j4PXYRVOBZD9LVOBQWcHWJKCCkB0PhJ9Oovkl7/LmjlVQfF78lT1WUq6y/QrQYPPyZeTBiB5tJY9Kgrtxwg38/0vOSI1gpt7rPXlHKu6BrlInYytJAXXtvBQ5dDOe3GgSma/nt8QCRTZJCasUFodIm2BCA3+PIFW3/no0dpf/mjiCrdT0Vd1LksR6r6PDVu/gzosvOAq80bWbxWJQ8tHx2/IaJPM+pgxodTFotgBNmUcJrA2Q/hysGjqeKHBbywVsB0K5frNXM1HxlFoSqo7wa7OiMyN4IS8K9oBWRkOnjZQgbfnaIdqU3GxCeJT6g6N9QANfyNMIgt2o3B5bt72bhVi2yHiIsFnfwVNbjj+Ju2qZnwpZkNu4w65PgG1A3RrSz6qak+/c1lNVKW8S7GaFyr4jKmlROrKb2gjk8o24OZRMoI="

sudo: required


before_install:
  - cd .travis/ && source setupTravis.sh && cd ../
  - sudo motion update || echo 'up to date'
  - sudo apt-get install -y cmake-data
  - sudo apt-get install -y libboost1.55-all-dev
  - sudo apt-get install -y libeigen3-dev
  - sudo apt-get install -y libgmp-dev
  - sudo apt-get install -y g++-6
  - sudo apt-get install -y libc++-dev
  - sudo apt-get install -y uuid-dev
  - sudo apt-get install -y openjdk-9-jre
  - git clone https://github.com/smtrat/carl.git && cd carl && mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_BUILD_TYPE=Release .. && make resources && make lib_carl -j2
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    sources:
      - boost-latest
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
  coverity_scan:
    project:
      name: "hypro/hypro"
      description: "Branch for coverity scan."
      notification_email: stefan.schupp@cs.rwth-aachen.de
      build_command_prepend: "cmake . $FLAGS -DCMAKE_CXX_COMPILER=g++-6"
      build_command: "make"
      branch_pattern: coverity_scan

before_script:

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi

