branches:
  only:
  - master

language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get install cmake

install: true

script: mkdir build && cd build && cmake .. && make
