language: cpp
branches:
  only:
  - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: hypro
    - DOXYFILE: $TRAVIS_BUILD_DIR/build/doc/Doxygen
    - GH_REPO_REF: github.com/hypro/hypro.git

notifications:
  email:
    recipients:
      - stefan.schupp@cs.rwth-aachen.de
  slack:
    rooms:
      - hypro:v2n2cgATRJJYPctLTL1MSfOn#github

sudo: required

addons:
  apt:
    sources:
      - boost-latest
      - george-edison55-precise-backports
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - doxygen
      - lcov
      - libboost1.55-all-dev
      - libeigen3-dev
      - libgmp-dev
      - libgtest-dev
      - g++-5
      - g++-6
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - clang-3.9
      - libglpk-dev
      - graphviz
      - texlive-latex-extra
      - texlive-latex-recommended

matrix:
  include:
    #- os: linux
    #  compiler: gcc
    #  env: COMPILER=g++-4.9
    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-5
    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-6 FLAGS=-DHYPRO_COVERAGE=ON
    - os: linux
      dist: trusty
      compiler: clang
      env: COMPILER=clang++-3.6
    - os: linux
      dist: trusty
      compiler: clang
      env: COMPILER=clang++-3.7
    - os: linux
      dist: trusty
      compiler: clang
      env: COMPILER=clang++-3.8
    - os: osx
      compiler: clang
      env: COMPILER=clang++-3.5

before_install:
  - cd .travis/ && source setupTravis.sh && cd ../

install:
  - git clone https://github.com/smtrat/carl.git && cd carl && mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release .. && make resources && make lib_carl VERBOSE=1

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build && cmake $FLAGS -DCMAKE_CXX_COMPILER=$COMPILER .. && make resources && make
  - make test

# Generate and deploy documentation
after_success:
  - cmake -DCREATE_DOC=ON ..
  - cd $TRAVIS_BUILD_DIR
  - chmod +x createAndDeployDocumentation.sh
  - ./createAndDeployDocumentation.sh
  # coveralls
  - chmod +x processCoverage.sh
  - ./processCoverage.sh
