language:
  -c++

branches:
  only:
  - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: hypro
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxygen.in
    - GH_REPO_REF: github.com/hypro/hypro.git

notifications:
  email:
    recipients:
      - stefan.schupp@cs.rwth-aachen.de
  slack:
    rooms:
      - hypro:v2n2cgATRJJYPctLTL1MSfOn#github

os:
  - linux
  - osx

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get install cmake gcc-4.9 g++-4.9 libboost1.55-all-dev libeigen3-dev libglpk-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - git clone https://github.com/smtrat/carl.git && cd carl && mkdir build && cd build && cmake .. && make lib_carl
  - cd ../../

install: true

before_script: true

script:
  - mkdir build && cd build && cmake .. && make
  - make test

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x createAndDeployDocumentation.sh
  - ./createAndDeployDocumentation.sh
