env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VrgSZAgTRTdH1rq0OHXHtArOA5SyLsJX9YA9O5c+PSXI/drMjc3pGsTIK3NA7xcyGaEIT+DjzV36yxvAz/3uurYkFtiz/sl1suziy6nSNBqvQSE01lBU9GnqHpkPg6/alnijG0Bf3KvXTdw5MmRaK+f9corNJAa+s1sP0rP7WMQ="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

language: cpp
branches:
  only:
  - coverity_scan

# Environment variables
env:
  global:
    - GH_REPO_NAME: hypro
    - DOXYFILE: $TRAVIS_BUILD_DIR/build/doc/Doxygen
    - GH_REPO_REF: github.com/hypro/hypro.git
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "VrgSZAgTRTdH1rq0OHXHtArOA5SyLsJX9YA9O5c+PSXI/drMjc3pGsTIK3NA7xcyGaEIT+DjzV36yxvAz/3uurYkFtiz/sl1suziy6nSNBqvQSE01lBU9GnqHpkPg6/alnijG0Bf3KvXTdw5MmRaK+f9corNJAa+s1sP0rP7WMQ="

notifications:
  email:
    recipients:
      - stefan.schupp@cs.rwth-aachen.de
  slack:
    rooms:
      - hypro:v2n2cgATRJJYPctLTL1MSfOn#github

sudo: required

addons:
  apt:
    sources:
      - boost-latest
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - doxygen
      - lcov
      - libboost1.55-all-dev
      - libeigen3-dev
      - libgmp-dev
      - libgtest-dev
      - g++-6
      - libc++-dev
      - graphviz
      - uuid-dev
      - openjdk-9-jre
  coverity_scan:
    project:
      name: "hypro/hypro"
      description: "<Your project description here>"
      notification_email: stefan.schupp@cs.rwth-aachen.de
      build_command_prepend: "mkdir build && cd build && cmake .."
      build_command: "make resources && make -j2"
      branch_pattern: coverity_scan

before_install:
  - cd .travis/ && source setupTravis.sh && cd ../
  - sudo motion update || echo 'up to date'
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - git clone https://github.com/smtrat/carl.git && cd carl && mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release .. && make resources && make lib_carl -j2

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build && cmake $FLAGS -DCMAKE_CXX_COMPILER=$COMPILER .. && make resources && make -j2

